<a href="https://colab.research.google.com/github/DOLLARDEV05/AI-LAB/blob/main/Attention%20is%20All%20You%20Need/Transformers/single_head_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

sentence = "My dog is a lazy dawg!"

tokens = sentence.lower().split()
print("Tokens:", tokens)

vocab = {word: idx for idx, word in enumerate(set(tokens))}
print("Vocab:", vocab)

token_ids = np.array([vocab[word] for word in tokens])
print("Token IDs:", token_ids)


Tokens: ['my', 'dog', 'is', 'a', 'lazy', 'dawg!']
Vocab: {'my': 0, 'lazy': 1, 'dawg!': 2, 'a': 3, 'dog': 4, 'is': 5}
Token IDs: [0 4 5 3 1 2]


In [2]:
# let's create some embeddings!

d_model = 4

# this will create a random matrix of small float values with dimension being
# rows = length of the sentence/token list, columns being the dimension we set
# that is the d_model = 4 where this is a hyperparameter, and for single head
# attention this is d_model = Q = K = V
embedding = np.random.rand(len(tokens),d_model)

print(embedding)

[[0.27064444 0.40691474 0.30218182 0.70027216]
 [0.78538329 0.81865222 0.73325928 0.85531961]
 [0.07303656 0.46161636 0.81293949 0.07031165]
 [0.78187511 0.30205625 0.51889201 0.65670206]
 [0.48348023 0.95997782 0.62813706 0.10745558]
 [0.82937072 0.28328431 0.11892493 0.3811553 ]]


In [3]:
embedding_token = np.array([[embedding[vocab[token]]] for token in tokens])
print(embedding_token)

[[[0.27064444 0.40691474 0.30218182 0.70027216]]

 [[0.48348023 0.95997782 0.62813706 0.10745558]]

 [[0.82937072 0.28328431 0.11892493 0.3811553 ]]

 [[0.78187511 0.30205625 0.51889201 0.65670206]]

 [[0.78538329 0.81865222 0.73325928 0.85531961]]

 [[0.07303656 0.46161636 0.81293949 0.07031165]]]
