<a href="https://colab.research.google.com/github/DOLLARDEV05/AI-LAB/blob/main/Attention%20is%20All%20You%20Need/Transformers/single_head_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

sentence = "My dog is a lazy dawg!"

tokens = sentence.lower().split()
print("Tokens:", tokens)

vocab = {word: idx for idx, word in enumerate(set(tokens))}
print("Vocab:", vocab)

token_ids = np.array([vocab[word] for word in tokens])
print("Token IDs:", token_ids)


Tokens: ['my', 'dog', 'is', 'a', 'lazy', 'dawg!']
Vocab: {'lazy': 0, 'is': 1, 'dawg!': 2, 'a': 3, 'dog': 4, 'my': 5}
Token IDs: [5 4 1 3 0 2]


In [3]:
# let's create some embeddings!

d_model = 4

# this will create a random matrix of small float values with dimension being
# rows = length of the sentence/token list, columns being the dimension we set
# that is the d_model = 4 where this is a hyperparameter, and for single head
# attention this is d_model = Q = K = V
embedding = np.random.rand(len(tokens),d_model)

print(embedding)

[[0.40797961 0.26245661 0.13230297 0.32211494]
 [0.5798123  0.74813028 0.55576371 0.05278673]
 [0.77841145 0.06417725 0.76213207 0.97529268]
 [0.4889171  0.51745525 0.78555116 0.92466429]
 [0.6445754  0.79719042 0.91560506 0.61567353]
 [0.84581249 0.5440232  0.1746567  0.90529765]]
