<a href="https://colab.research.google.com/github/DOLLARDEV05/AI-LAB/blob/main/Attention_is_All_You_Need/Transformers/multiheadattention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
print("hello multihead attention")

hello multihead attention


In [20]:
import numpy as np
import math

sentence = "My cat is lazy"

tokens = sentence.lower().split()

vocab = {word: idx for idx, word in enumerate(set(tokens))}

token_ids = np.array([vocab[word] for word in tokens])

d_model = 4
embedding = np.random.rand(len(tokens),d_model)

embedding_token = np.array([embedding[vocab[token]] for token in tokens])


for embedding in range(len(embedding_token)):
  for value in range(d_model):
    if value % 2 == 0:
      temp = math.sin(embedding/10000**((2*(value//2))/d_model))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    elif value % 2 == 1:
      temp = math.cos(embedding/10000**((2*(value//2))/d_model))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    else:
      print("error")

W_Q = np.random.rand(d_model,d_model)
W_K = np.random.rand(d_model,d_model)
W_V = np.random.rand(d_model,d_model)


Q = embedding_token @ W_Q
K = embedding_token @ W_K
V = embedding_token @ W_V

pre_softmax = (Q @ K.T)/np.sqrt(d_model)

for vector in pre_softmax:
  row_max = np.max(vector,axis=0)
  for element in range(len(vector)):
    vector[element] = np.exp(vector[element] - row_max)
  vector /= np.sum(vector)


softmax = pre_softmax.copy()


In [21]:
# next steps make two single head attention work in parallel
# and also make the simple logic of hstacking the outputs of each head and then
# matmul with the weighted matrix Wo. that is it for the multi head!

In [22]:
import numpy as np
import math

sentence = "My cat is lazy"

tokens = sentence.lower().split()

vocab = {word: idx for idx, word in enumerate(set(tokens))}

token_ids = np.array([vocab[word] for word in tokens])

d_model = 4
embedding = np.random.rand(len(tokens),d_model)

embedding_token = np.array([embedding[vocab[token]] for token in tokens])


for embedding in range(len(embedding_token)):
  for value in range(d_model):
    if value % 2 == 0:
      temp = math.sin(embedding/10000**((2*(value//2))/d_model))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    elif value % 2 == 1:
      temp = math.cos(embedding/10000**((2*(value//2))/d_model))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    else:
      print("error")

W_Q2 = np.random.rand(d_model,d_model)
W_K2 = np.random.rand(d_model,d_model)
W_V2 = np.random.rand(d_model,d_model)


Q = embedding_token @ W_Q2
K = embedding_token @ W_K2
V = embedding_token @ W_V2

pre_softmax2 = (Q @ K.T)/np.sqrt(d_model)

for vector in pre_softmax2:
  row_max = np.max(vector,axis=0)
  for element in range(len(vector)):
    vector[element] = np.exp(vector[element] - row_max)
  vector /= np.sum(vector)


softmax2 = pre_softmax2.copy()
print(softmax,"\n\n\n\n\n",softmax2)

[[0.12162996 0.5681372  0.29353068 0.01670215]
 [0.12515436 0.57109301 0.28717527 0.01657735]
 [0.11938587 0.60149863 0.26785603 0.01125947]
 [0.20084299 0.45238041 0.28970759 0.05706901]] 




 [[0.11389249 0.51473968 0.36712964 0.00423819]
 [0.08660188 0.5315276  0.37917468 0.00269584]
 [0.124762   0.46701521 0.39496205 0.01326073]
 [0.23497552 0.33751503 0.31849388 0.10901557]]
