<a href="https://colab.research.google.com/github/DOLLARDEV05/AI-LAB/blob/main/Attention_is_All_You_Need/Transformers/multiheadattention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import math

sentence = "My cat is lazy"

tokens = sentence.lower().split()

vocab = {word: idx for idx, word in enumerate(set(tokens))}

token_ids = np.array([vocab[word] for word in tokens])

d_v = 4
d_k = 4
embedding = np.random.rand(len(tokens),d_k)

embedding_token = np.array([embedding[vocab[token]] for token in tokens])


for embedding in range(len(embedding_token)):
  for value in range(d_k):
    if value % 2 == 0:
      temp = math.sin(embedding/10000**((2*(value//2))/d_k))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    elif value % 2 == 1:
      temp = math.cos(embedding/10000**((2*(value//2))/d_k))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    else:
      print("error")

W_Q = np.random.rand(d_k,d_k)
W_K = np.random.rand(d_k,d_k)
W_V = np.random.rand(d_k,d_v)


Q1 = embedding_token @ W_Q
K1 = embedding_token @ W_K
V1 = embedding_token @ W_V

pre_softmax = (Q1 @ K1.T)/np.sqrt(d_k)

for vector in pre_softmax:
  row_max = np.max(vector,axis=0)
  for element in range(len(vector)):
    vector[element] = np.exp(vector[element] - row_max)
  vector /= np.sum(vector)

softmax = pre_softmax.copy()
attention1 = softmax @ V1


In [6]:
# next steps make two single head attention work in parallel
# and also make the simple logic of hstacking the outputs of each head and then
# matmul with the weighted matrix Wo. that is it for the multi head!

In [7]:

d_k = 4
d_v = 4
embedding2 = np.random.rand(len(tokens),d_k)

embedding_token2 = np.array([embedding2[vocab[token]] for token in tokens])


for embedding2 in range(len(embedding_token2)):
  for value in range(d_k):
    if value % 2 == 0:
      temp = math.sin(embedding2/10000**((2*(value//2))/d_k))
      embedding_token2[embedding2,value]=embedding_token2[embedding2,value]+temp
    elif value % 2 == 1:
      temp = math.cos(embedding2/10000**((2*(value//2))/d_k))
      embedding_token2[embedding2,value]=embedding_token2[embedding2,value]+temp
    else:
      print("error")

W_Q2 = np.random.rand(d_k,d_k)
W_K2 = np.random.rand(d_k,d_k)
W_V2 = np.random.rand(d_k,d_v)


Q2 = embedding_token2 @ W_Q2
K2 = embedding_token2 @ W_K2
V2 = embedding_token2 @ W_V2

pre_softmax2 = (Q2 @ K2.T)/np.sqrt(d_k)

for vector in pre_softmax2:
  row_max = np.max(vector,axis=0)
  for element in range(len(vector)):
    vector[element] = np.exp(vector[element] - row_max)
  vector /= np.sum(vector)


softmax2 = pre_softmax2.copy()
attention2 = softmax2 @ V2
print(attention1,"\n\n\n\n\n",attention2)

[[2.19409185 1.58922412 2.25522745 2.08584429]
 [2.27062565 1.63884744 2.4192945  2.19322497]
 [2.23362436 1.61686817 2.37395346 2.16136552]
 [2.13661529 1.55915869 2.21926085 2.0584711 ]] 




 [[2.47268497 2.31069329 2.62598169 0.98362336]
 [2.48078339 2.3159054  2.64201373 0.98818159]
 [2.48097775 2.31514981 2.64237559 0.98795207]
 [2.44119944 2.28823406 2.56368836 0.96456375]]


In [8]:
# let's build multihead attention using these 2 single heads
d_model = 8
head_count = 2
multihead_concat = np.hstack((attention1,attention2))
Wo = np.random.rand((d_v*head_count),d_model)
twohead_attention = multihead_concat @ Wo

print(twohead_attention)


[[ 6.22777553 10.88303612  5.56724201  8.96095745  8.68960264 10.54191176
   9.22992021  5.92578856]
 [ 6.37397894 11.2053997   5.74213567  9.15134465  8.89992414 10.90573632
   9.38088719  6.0848721 ]
 [ 6.33017771 11.11144582  5.688958    9.08357709  8.8288758  10.79056386
   9.32464339  6.03910847]
 [ 6.1186441  10.6912329   5.47898962  8.79935428  8.52857801 10.35249616
   9.04542051  5.82026677]]
