<a href="https://colab.research.google.com/github/DOLLARDEV05/AI-LAB/blob/main/Attention_is_All_You_Need/Transformers/multiheadattention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
print("hello multihead attention")

hello multihead attention


In [15]:
import numpy as np
import math

sentence = "My cat is lazy"

tokens = sentence.lower().split()

vocab = {word: idx for idx, word in enumerate(set(tokens))}

token_ids = np.array([vocab[word] for word in tokens])

d_v = 4
d_k = 4
embedding = np.random.rand(len(tokens),d_k)

embedding_token = np.array([embedding[vocab[token]] for token in tokens])


for embedding in range(len(embedding_token)):
  for value in range(d_k):
    if value % 2 == 0:
      temp = math.sin(embedding/10000**((2*(value//2))/d_k))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    elif value % 2 == 1:
      temp = math.cos(embedding/10000**((2*(value//2))/d_k))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    else:
      print("error")

W_Q = np.random.rand(d_k,d_k)
W_K = np.random.rand(d_k,d_k)
W_V = np.random.rand(d_k,d_v)


Q1 = embedding_token @ W_Q
K1 = embedding_token @ W_K
V1 = embedding_token @ W_V

pre_softmax = (Q1 @ K1.T)/np.sqrt(d_k)

for vector in pre_softmax:
  row_max = np.max(vector,axis=0)
  for element in range(len(vector)):
    vector[element] = np.exp(vector[element] - row_max)
  vector /= np.sum(vector)

softmax = pre_softmax.copy()
attention1 = softmax @ V1


In [16]:
# next steps make two single head attention work in parallel
# and also make the simple logic of hstacking the outputs of each head and then
# matmul with the weighted matrix Wo. that is it for the multi head!

In [17]:
import numpy as np
import math

sentence = "My cat is lazy"

tokens = sentence.lower().split()

vocab = {word: idx for idx, word in enumerate(set(tokens))}

token_ids = np.array([vocab[word] for word in tokens])

d_k = 4
d_v = 4
embedding = np.random.rand(len(tokens),d_k)

embedding_token = np.array([embedding[vocab[token]] for token in tokens])


for embedding in range(len(embedding_token)):
  for value in range(d_k):
    if value % 2 == 0:
      temp = math.sin(embedding/10000**((2*(value//2))/d_k))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    elif value % 2 == 1:
      temp = math.cos(embedding/10000**((2*(value//2))/d_k))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    else:
      print("error")

W_Q2 = np.random.rand(d_k,d_k)
W_K2 = np.random.rand(d_k,d_k)
W_V2 = np.random.rand(d_k,d_v)


Q2 = embedding_token @ W_Q2
K2 = embedding_token @ W_K2
V2 = embedding_token @ W_V2

pre_softmax2 = (Q2 @ K2.T)/np.sqrt(d_k)

for vector in pre_softmax2:
  row_max = np.max(vector,axis=0)
  for element in range(len(vector)):
    vector[element] = np.exp(vector[element] - row_max)
  vector /= np.sum(vector)


softmax2 = pre_softmax2.copy()
attention2 = softmax2 @ V2
print(attention1,"\n\n\n\n\n",attention2)

[[3.19622079 3.08819507 3.01143329 2.17384355]
 [3.20543865 3.09960205 3.02361909 2.18359652]
 [3.05533055 2.96778048 2.81219874 2.04217981]
 [3.03252074 2.9429619  2.7809058  2.01893778]] 




 [[3.04407154 1.42306164 2.91532602 1.83015131]
 [3.06676737 1.43097474 2.95113814 1.8511011 ]
 [3.06798119 1.43399075 2.94216936 1.84704184]
 [2.99225527 1.39525724 2.86762299 1.79837031]]


In [18]:
# let's build multihead attention using these 2 single heads
d_model = 8
head_count = 2
multihead_concat = np.hstack((attention1,attention2))
Wo = np.random.rand((d_v*head_count),d_model)
twohead_attention = multihead_concat @ Wo

print(twohead_attention)


[[13.79048442 10.63162644  9.97923988 11.42330476  9.15735701  9.41447057
  12.17245109 10.94016995]
 [13.88721421 10.69622733 10.04279074 11.49350904  9.19967572  9.46412848
  12.25260762 10.99284277]
 [13.48431392 10.36822137  9.69914249 11.0961861   8.83482279  9.09775769
  11.89271088 10.58338483]
 [13.23210711 10.19115211  9.54386041 10.91103372  8.71521751  8.97757714
  11.68903241 10.42805158]]
