<a href="https://colab.research.google.com/github/DOLLARDEV05/AI-LAB/blob/main/Attention_is_All_You_Need/Transformers/single_head_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

sentence = "My dog is a lazy dawg!"

tokens = sentence.lower().split()
print("Tokens:", tokens)

vocab = {word: idx for idx, word in enumerate(set(tokens))}
print("Vocab:", vocab)

token_ids = np.array([vocab[word] for word in tokens])
print("Token IDs:", token_ids)


Tokens: ['my', 'dog', 'is', 'a', 'lazy', 'dawg!']
Vocab: {'my': 0, 'dawg!': 1, 'a': 2, 'lazy': 3, 'is': 4, 'dog': 5}
Token IDs: [0 5 4 2 3 1]


In [9]:
# let's create some embeddings!

d_model = 4

# this will create a random matrix of small float values with dimension being
# rows = length of the sentence/token list, columns being the dimension we set
# that is the d_model = 4 where this is a hyperparameter, and for single head
# attention this is d_model = Q = K = V
embedding = np.random.rand(len(tokens),d_model)

print(embedding)

[[0.57315095 0.8797169  0.5390022  0.577225  ]
 [0.97503785 0.20233534 0.80432022 0.9533034 ]
 [0.51117782 0.8481676  0.89649732 0.7489238 ]
 [0.99081032 0.4798701  0.69701366 0.4191498 ]
 [0.89590477 0.83588058 0.19950745 0.32108781]
 [0.88267649 0.0384103  0.26093202 0.07889628]]


In [10]:
embedding_token = np.array([embedding[vocab[token]] for token in tokens])
print(embedding_token)

[[0.57315095 0.8797169  0.5390022  0.577225  ]
 [0.88267649 0.0384103  0.26093202 0.07889628]
 [0.89590477 0.83588058 0.19950745 0.32108781]
 [0.51117782 0.8481676  0.89649732 0.7489238 ]
 [0.99081032 0.4798701  0.69701366 0.4191498 ]
 [0.97503785 0.20233534 0.80432022 0.9533034 ]]


In [11]:
# let's convert the maths of positional encoding into code successful

import math

for embedding in range(len(embedding_token)):
  for value in range(d_model):
    if value % 2 == 0:
      temp = math.sin(embedding/10000**((2*(value//2))/d_model))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    elif value % 2 == 1:
      temp = math.cos(embedding/10000**((2*(value//2))/d_model))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    else:
      print("error")
print(embedding_token)

[[ 0.57315095  1.8797169   0.5390022   1.577225  ]
 [ 1.72414747  0.57871261  0.27093185  1.07884628]
 [ 1.8052022   0.41973374  0.21950611  1.32088782]
 [ 0.65229783 -0.14182489  0.92649282  1.74847383]
 [ 0.23400782 -0.17377352  0.737003    1.41834991]
 [ 0.01611358  0.48599753  0.85429939  1.95205366]]


In [12]:
x = 0 // 2
y = 1 // 2
z = 2 // 2
p = 3 // 2
q = 4 // 2

# how positional encoding uses floor division to have similar values given to the
# sin and cos fuction to have pi/2 shifted sin and cos waves that also dipicts a
# circle idk if this is necessary to mention here

print(x,y,z,p,q)

# was just showcasing where i was stuck in positional encoding and why it matter

0 0 1 1 2
