<a href="https://colab.research.google.com/github/DOLLARDEV05/AI-LAB/blob/main/Attention%20is%20All%20You%20Need/Transformers/single_head_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

sentence = "My dog is a lazy dawg!"

tokens = sentence.lower().split()
print("Tokens:", tokens)

vocab = {word: idx for idx, word in enumerate(set(tokens))}
print("Vocab:", vocab)

token_ids = np.array([vocab[word] for word in tokens])
print("Token IDs:", token_ids)


Tokens: ['my', 'dog', 'is', 'a', 'lazy', 'dawg!']
Vocab: {'is': 0, 'my': 1, 'dawg!': 2, 'dog': 3, 'lazy': 4, 'a': 5}
Token IDs: [1 3 0 5 4 2]


In [15]:
# let's create some embeddings!

d_model = 4

# this will create a random matrix of small float values with dimension being
# rows = length of the sentence/token list, columns being the dimension we set
# that is the d_model = 4 where this is a hyperparameter, and for single head
# attention this is d_model = Q = K = V
embedding = np.random.rand(len(tokens),d_model)

print(embedding)

[[0.2971035  0.79492616 0.60250917 0.17013277]
 [0.31570748 0.07792668 0.58472469 0.65704644]
 [0.93464365 0.95750308 0.7352807  0.21200516]
 [0.73433249 0.17522748 0.66015747 0.23828552]
 [0.64706101 0.96588552 0.30879194 0.25497137]
 [0.99267938 0.03707734 0.27253188 0.07905146]]


In [16]:
embedding_token = np.array([embedding[vocab[token]] for token in tokens])
print(embedding_token)

[[0.31570748 0.07792668 0.58472469 0.65704644]
 [0.73433249 0.17522748 0.66015747 0.23828552]
 [0.2971035  0.79492616 0.60250917 0.17013277]
 [0.99267938 0.03707734 0.27253188 0.07905146]
 [0.64706101 0.96588552 0.30879194 0.25497137]
 [0.93464365 0.95750308 0.7352807  0.21200516]]


In [17]:
# let's convert the maths of positional encoding into code successful

import math

for embedding in range(len(embedding_token)):
  for value in range(d_model):
    if value % 2 == 0:
      temp = math.sin(embedding/10000**((2*value)/d_model))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    elif value % 2 == 1:
      temp = math.cos(embedding/10000**((2*value)/d_model))
      embedding_token[embedding,value]=embedding_token[embedding,value]+temp
    else:
      print("error")
print(embedding_token)

[[ 0.31570748  1.07792668  0.58472469  1.65704644]
 [ 1.57580348  1.17517748  0.66025747  1.23828552]
 [ 1.20640092  1.79472617  0.60270917  1.17013277]
 [ 1.13379939  1.03662738  0.27283188  1.07905146]
 [-0.10974149  1.96508562  0.30919194  1.25497137]
 [-0.02428063  1.95625334  0.7357807   1.21200516]]
